resources:
  - ../../base

namespace: dev
namePrefix: dev-

commonLabels:
  app.kubernetes.io/name: s3-client-application
  app.kubernetes.io/version: v0.3.0

patches:
  - target: 
      kind: Deployment
      name: bucket-loader
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bucket-loader
      spec:
        template:
          spec:
            containers:
              - name: bucket-loader
                image: quay.io/murph830/s3-client-application:v0.3.0
  - target: 
      kind: Bucket
      name: bucket
    patch: |-
      apiVersion: example.upbound.io/v1alpha1
      kind: Bucket
      metadata:
        name: bucket
      spec:
        parameters:
          bucketName: murph-loader-test
        writeConnectionSecretToRef:
          name: bucket-secret
          
secretGenerator:
  - name: aws-credentials
    envs:
      - .env.secret