apiVersion: example.upbound.io/v1alpha1
kind: Space
metadata:
  name: azure-space
spec:
  compositionSelector:
    matchLabels:
      spaces.upbound.io/cluster-type: aks
  parameters:
    clusterId: azure-spoke-03
    account: crossplane-by-example
    version: "1.1.0"
    host: proxy.upbound.opusdavei.org
    spacesPullSecretRef:
      name: upbound-pull-secret
      namespace: upbound-system
    helmCredentialsSecretRef:
      name: helm-pull-secret
      namespace: upbound-system
