apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webapp
  name: bucket-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webapp
    spec:
      containers:
        - name: bucket-loader
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: bucket-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access-key-id
                  name: aws-credentials
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: session-token
                  name: aws-credentials
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-access-key
                  name: aws-credentials
          image: quay.io/murph830/s3-client-application:v0.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
