apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webapp
  name: bucket-loader
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: webapp
  type: ClusterIP